import { test,expect } from "@playwright/test";
test("Create Lead - Leaftaps application",async({page})=>
{
    await page.goto('https://leaftaps.com/opentaps/control/main')
    await page.locator('#username').fill('Demosalesmanager')
    await page.locator('#password').fill('crmsfa')
    await page.locator('.decorativeSubmit').click()
    await page.locator("//a[contains(text(),'CRM/SFA')]").click()
    await page.getByRole("link",{name:"Leads"}).click()
    await page.getByRole("link",{name:"Create Lead"}).click()
    await page.locator('//input[@id="createLeadForm_companyName"]').fill("Infosys")
    await page.locator('//input[@id="createLeadForm_firstName"]').fill("Chinthana")
    await page.locator('//input[@id="createLeadForm_lastName"]').fill("JS")
    await page.locator('//input[@id="createLeadForm_personalTitle"]').fill("Mrs")
    await page.locator('//input[@id="createLeadForm_generalProfTitle"]').fill("Test Analyst")
    await page.locator('//input[@id="createLeadForm_annualRevenue"]').fill("1000000")
    await page.locator('//input[@id="createLeadForm_departmentName"]').fill("IT")
    await page.locator('//input[@id="createLeadForm_primaryPhoneNumber"]').fill("99409")
    await page.locator('//input[@name="submitButton"]').click()
    await page.title()
    await expect(page.locator("//span[@id='viewLead_companyName_sp']")).toContainText("Infosys")
    await expect(page.locator("//span[@id='viewLead_firstName_sp']")).toContainText("Chinthana")
    await expect(page.locator("//span[@id='viewLead_lastName_sp']")).toContainText("JS")
    await expect (page.locator("//span[@id='viewLead_statusId_sp']")).toContainText("Assigned")
    await page.waitForTimeout(3000)
})
test("Edit Lead - Leaftaps application",async({page})=>
{
    await page.goto('https://leaftaps.com/opentaps/control/main')
    await page.locator('#username').fill('Demosalesmanager')
    await page.locator('#password').fill('crmsfa')
    await page.locator('.decorativeSubmit').click()
    await page.locator("//a[contains(text(),'CRM/SFA')]").click()
    await page.getByRole("link",{name:"Leads"}).click()  
    await page.getByRole("link",{name:"Find Leads"}).click()
    await page.getByRole("textbox",{name:"First name"}).nth(1).fill("Chinthana")
    await page.getByRole("button",{name:"Find Leads"}).click()
    await page.locator('//td[@class="x-grid3-col x-grid3-cell x-grid3-td-partyId x-grid3-cell-first "]/div/a[@class="linktext"]').nth(0).click()
    await page.getByRole("link",{name:"Edit"}).click()
    await page.locator('#updateLeadForm_companyName').fill("Virtusa")
    await page.locator('#updateLeadForm_annualRevenue').fill("30000000")
    await page.locator('#updateLeadForm_departmentName').fill("Delivery")
    await page.locator('#updateLeadForm_description').fill("Editing the information")
    await page.getByRole("button",{name:"Update"}).click()
    console.log(await page.title())
    await expect(page.locator('//span[@id="viewLead_companyName_sp"]')).toContainText('Virtusa')
    await expect(page.locator('//span[@id="viewLead_annualRevenue_sp"]')).toContainText('$30,000,000.00')
    await expect(page.locator('//span[@id="viewLead_departmentName_sp"]')).toContainText('Delivery')
    await expect(page.locator('//span[@id="viewLead_description_sp"]')).toContainText('Editing the information')

})


test("Sales force Create a new account - Username and Password steps",async({page})=>
{
    await page.goto('https://login.salesforce.com/')
    await page.getByLabel("Username",{exact:true}).fill('jsjayashruthi176.2bfafdd1d645@agentforce.com')
    await page.getByLabel("Password",{exact:true}).fill('Mahatma14')
    await page.getByRole("button",{name:"Log In"}).click()
    await page.waitForTimeout(3000)
}
)

test.use({storageState:"Data/login-salesforce.json"})
test("Create an account - Salesforce",async({page})=>
{
    page.goto('https://orgfarm-6c52dab5cf-dev-ed.develop.my.salesforce-setup.com/lightning/setup/SetupOneHome/home?SetupDomainReload=1&SetupDomainProbePassed=true')
    page.waitForTimeout(5000)
    await expect (page.locator('.slds-icon-waffle')).toBeVisible({timeout:15000})
    await page.locator('.slds-icon-waffle').click()
    console.log(await page.url())
    console.log(await page.title())
    await page.getByText("View All",{exact:true}).click()
    await page.getByPlaceholder("Search apps or items...",{exact:true}).fill('Service')
    await page.waitForTimeout(8000)
    await expect (page.locator('//mark[text()="Service"]').nth(0)).toBeVisible({timeout:8000})
    await page.locator('//mark[text()="Service"]').nth(0).click()
    await expect (page.locator('[title="Accounts"]')).toBeVisible({timeout:8000})
    await page.locator('[title="Accounts"]').click()
    await expect (page.getByRole("button",{name:"New"})).toBeVisible({timeout:10000})
    await page.getByRole("button",{name:"New"}).click()
    await expect (page.locator('[name="Name"]')).toBeVisible({timeout:6000})
    await  page.locator('[name="Name"]').fill('Chinthana')
    await page.waitForTimeout(6000)
    await page.locator('//button[text()="Save"]').click()
    await expect (page.locator('//span[contains(text(),"was created")]')).toBeVisible()
    await page.waitForTimeout(8000)
})
